
// This file has been generated by the GUI designer. Do not modify.
namespace Psolver
{
	public partial class Scheduler
	{
		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Calendar calendar5;

		private global::Gtk.Label GtkLabel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Psolver.Scheduler
			this.Name = "Psolver.Scheduler";
			this.Title = global::Mono.Unix.Catalog.GetString("Scheduler");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Psolver.Scheduler.Gtk.Container+ContainerChild
			this.frame3 = new global::Gtk.Frame();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.calendar5 = new global::Gtk.Calendar();
			this.calendar5.CanFocus = true;
			this.calendar5.Name = "calendar5";
			this.calendar5.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox1.Add(this.calendar5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.calendar5]));
			w1.Position = 2;
			w1.Expand = false;
			w1.Fill = false;
			this.GtkAlignment.Add(this.vbox1);
			this.frame3.Add(this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>GtkFrame</b>");
			this.GtkLabel.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel;
			this.Add(this.frame3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 503;
			this.DefaultHeight = 411;
			this.Show();
		}
	}
}
